import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-sans)"],
        serif: ["serif"],
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        yale_blue: {
          "100": "#040d17",
          "200": "#07192e",
          "300": "#0b2644",
          "400": "#0f325b",
          "500": "#134074",
          "600": "#1d63b3",
          "700": "#3c88df",
          "800": "#7db0ea",
          "900": "#bed7f4",
          DEFAULT: "#134074",
        },
        berkeley_blue: {
          "100": "#040a13",
          "200": "#081425",
          "300": "#0b1e38",
          "400": "#0f284b",
          "500": "#13315c",
          "600": "#21559f",
          "700": "#397bd6",
          "800": "#7ba7e4",
          "900": "#bdd3f1",
          DEFAULT: "#13315c",
        },
        oxford_blue: {
          "100": "#02080e",
          "200": "#050f1c",
          "300": "#07172a",
          "400": "#091e38",
          "500": "#0b2545",
          "600": "#174e90",
          "700": "#2375da",
          "800": "#6ca3e7",
          "900": "#b5d1f3",
          DEFAULT: "#0b2545",
        },
        powder_blue: {
          "100": "#17222c",
          "200": "#2e4459",
          "300": "#456685",
          "400": "#6088ad",
          "500": "#8da9c4",
          "600": "#a3bad0",
          "700": "#baccdc",
          "800": "#d1dde7",
          "900": "#e8eef3",
          DEFAULT: "#8da9c4",
        },
        mint_cream: {
          "100": "#283b24",
          "200": "#507749",
          "300": "#7dab75",
          "400": "#b5cfb1",
          "500": "#eef4ed",
          "600": "#f1f6f0",
          "700": "#f4f8f4",
          "800": "#f8faf7",
          "900": "#fbfdfb",
          DEFAULT: "#eef4ed",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
